# Generated by Django 6.0.7 on 2026-08-28 14:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('global_id', models.UUIDField(unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(db_column='NAME_SECTION', max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=100, unique=True)),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('blocked', 'Blocked'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('estimated_time_to_capture', models.FloatField(blank=True, help_text='Estimated capture time in hours', null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('km_completed', models.FloatField(default=0.0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grids', to=settings.AUTH_USER_MODEL)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='backend.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('total_km_reviewed', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.authority')),
            ],
            options={
                'ordering': ['authority', 'day'],
                'constraints': [models.UniqueConstraint(fields=('authority', 'day'), name='unique_review_authority_day')],
            },
        ),
    ]
