# Generated by Django 6.0.7 on 2026-08-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority',
            name='global_id',
        ),
    ]
