# Generated by Django 6.0.7 on 2026-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_authority_global_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_authority_day',
        ),
        migrations.AddField(
            model_name='grid',
            name='km_to_digitize',
            field=models.FloatField(default=0.0, help_text='Cached street length inside this grid in kilometers.'),
        ),
        migrations.AddField(
            model_name='grid',
            name='percentage_of_total_streets',
            field=models.FloatField(default=0.0, help_text='Percentage of Authority street length represented by this grid.'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('authority', 'day'), name='unique_authority_review_day'),
        ),
    ]
