# Generated by Django 6.0.7 on 2026-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_review_unique_review_authority_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='estimated_completion_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
